server:
  port: 8040
  compression:
    enabled: true
  
spring:
  application:
    name: artist
  devtools:
    livereload:
      enabled: false
    add-properties: false
  flyway:
    baselineOnMigrate: true
  web:
    resources:
      add-mappings: false
springdoc:
  api-docs:
    enabled: true
    path: /apidocs
  swagger-ui:
    enabled: true
    path: /apidocs.html
