server:
  port: 8040
  
spring:
  application:
    name: artist
  r2dbc:
    url: r2dbc:postgresql://beatbuddy.io.vn:18000/beatbuddy_user
    username: beatbuddy
    password: 9258605ccdf074ea139bcb8f3a813d1a
  devtools:
    livereload:
      enabled: false
    add-properties: false