spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:18000/beatbuddy_user
    username: beatbuddy
    password: 9258605ccdf074ea139bcb8f3a813d1a
  flyway:
    url: jdbc:postgresql://localhost:18000/beatbuddy_user
    user: beatbuddy
    password: 9258605ccdf074ea139bcb8f3a813d1a
