CREATE TABLE artists (
	pk_id uuid DEFAULT gen_random_uuid() NOT NULL,
	id bpchar(16) NOT NULL,
	urn varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	is_verified bool DEFAULT false NOT NULL,
	is_public bool DEFAULT false NOT NULL,
	real_name varchar(255) NULL,
	birth_date date NULL,
	biography varchar(250) NULL,
	description text NULL,
	nationality varchar(255) NULL,
	thumbnail varchar(255) NULL,
	background varchar(255) NULL,
	total_likes int8 DEFAULT 0 NOT NULL,
	total_views int8 DEFAULT 0 NOT NULL,
	total_shares int8 DEFAULT 0 NOT NULL,
	ref_code varchar(100) NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_by varchar(255) NULL,
	updated_by varchar(255) NULL,
	CONSTRAINT artists_pk PRIMARY KEY (pk_id),
	CONSTRAINT artists_unq_id UNIQUE (id),
	CONSTRAINT artists_unq_ref_code UNIQUE (ref_code),
	CONSTRAINT artists_unq_urn UNIQUE (urn)
);
